### ISSUE TITLE
timeout when send msg to another local client

### ISSUE THREAD

**Issue by BruceChar** [nknorg/nkn-sdk-js#14]
I create and run a receiver client with  onMessage event.
// receiver.js
```javaScript
let receiver = new nkn.Client({
  identifier: 'Char',
  seed: 'generated seed'
})
receiver.onConnect(() => {
  console.log('-----------receiver ready----------')
})
receiver.onMessage(({src, payload}) => {
  console.log('receive message:', payload, 'from:', src)
  return 'Well received'
})
```
And run another client, setting the responseTimeout = 0. But I cannot get the response and client reconnect after a long time.
```javaScript
let receiver = 'reveiver addr'     
client.onConnect(() => {      
  console.log('-------------client ready-------------')     
  client.send(receiver, 'Hello receiver', {     
    responseTimeout: 0      
  }).then(re => {      
    console.log('send result:', re)      
  }).catch(err => {      
    console.error('send error:', err)      
  })    
})  
``` 
Any problem?

**Comment by yilunzhang** [comment]
Does the examples/client.js works for you? You should be able to run it with nodejs:

```
> node examples/client.js 
Secret seed: b6f2373f188dc76fd03382410ccafd70f93a1a999613e35f3a83be260e02ce2a
Send message from alice.61fcbba00e56108e52b315add4f91efc778ed92455ee922d18f4948286e514f3 to bob.05ef321a4a13a6551895ffe28f9a41a560dc30cfe249443aa0ce61791539ee04
Receive encrypted message "Hello world!" from alice.61fcbba00e56108e52b315add4f91efc778ed92455ee922d18f4948286e514f3 after 149 ms
Receive reply "Well received!" from bob.05ef321a4a13a6551895ffe28f9a41a560dc30cfe249443aa0ce61791539ee04 after 312 ms
```

If so, could you please provide a minimal piece code that can reproduce the problem? The code snippet you provided seems good, but there might be other problem like passing the wrong address, etc.

**Comment by BruceChar** [comment]
@yilunzhang I think yes!Since I run the sender and receiver in one node process is ok!It looks like an route delay problem, when I use MultiClient it is OK too. And  does NKN support for offline message?In my test the receiver cannot receiver the message that sender sent before.

**Comment by yilunzhang** [comment]
Yes it does! You can check msgHoldingSeconds in docs: https://docs.nkn.org/nkn-sdk-js/

**Comment by BruceChar** [comment]
@yilunzhang Cool！As NKN is a tokenize network, how does the clients communication pay the token or it  just for some special service？Like holding the offline msg in the node. What's the  difference among Client , MultiClient and Wallet? Any documents in detail? And any ideal about the problem of the local client timeout in this issue? Does I only can use MultiClient in local test?

**Comment by yilunzhang** [comment]
The relay service (client and multiclient) is free because node will be able to earn mining rewards when relaying for clients. Some other service (e.g. https://github.com/nknorg/tuna) that requires direct connection is not free because the traffic cannot be used for mining.

You can use client and multiclient in production. Actually we are already using it in a few of our products like nMobile, nCDN, etc. Also there are community projects using multiclient for communication, e.g. d-chat.

> And any ideal about the problem of the local client timeout in this issue?

Could you please provide a minimal piece code that can reproduce the problem? The code snippet you provided seems good, but there might be other problem like passing the wrong address, etc.

**Comment by BruceChar** [comment]
@yilunzhang Ha! I miss out the identifier. What's the difference of msgHoldingSeconds between SendOptions  and ClientsOptions? Do I need to set the option in src client and dest client at the same time? And is it ok for developer only use nkn-sdk-* to build a p2p socail application?

**Comment by yilunzhang** [comment]
> What's the difference of msgHoldingSeconds between SendOptions and ClientsOptions?

The one sendOptions in send options will override the one in clientOptions. If you want the client to always have some msgHoldingSeconds, just set clientOptions. But if you want different message to behave differently, you can set the one in sendOptions.

> Do I need to set the option in src client and dest client at the same time? 

No need, you only need to set it on sender.

> And is it ok for developer only use nkn-sdk-* to build a p2p socail application?

Of course :)

**Comment by BruceChar** [comment]
Awesome!
