### ISSUE TITLE
这个错误是什么意思？TypeError: invalid edPk length

### ISSUE THREAD

**Issue by zsp042** [nknorg/nkn-sdk-js#31]
见下面的截图

![image](https://user-images.githubusercontent.com/52188840/89716258-0c446f00-d9de-11ea-8f43-1a7c9cbe3567.png)

**Comment by yilunzhang** [comment]
你 send 的地址不对~ `client.send` 的第一个参数是 addr，传入的应该是对方 client 的 `client.addr` (即 `identifier.pubkey`)，你这里的 address 缺失了 `.pubkey` 部分，只有 identifier 前缀，所以报错
