### ISSUE TITLE
支持多播吗，也就是只给地址address，不给identifier

### ISSUE THREAD

**Issue by zsp042** [nknorg/nkn-sdk-js#32]
比如，我发一条微信，别人所有登录的设备都应该收到

**Comment by yilunzhang** [comment]
如果多个设备共享 identifier 和 pubkey，那么所有在线的设备都会收到消息。
如果多个设备只共享 pubkey，但是使用的是不同的 identifier，那么没法同时收到消息。

**Comment by zsp042** [comment]
看到可以用topic订阅了，多谢
