### ISSUE TITLE
 Send response error: Error: failed to send with any client: AssertionError: Failure: Cannot coerce to Uint8Array: 

### ISSUE THREAD

**Issue by eyun-tv** [nknorg/nkn-sdk-js#35]
Send response error: Error: failed to send with any client: AssertionError: Failure: Cannot coerce to Uint8Array: 

```
Send response error: Error: failed to send with any client: AssertionError: Failure: Cannot coerce to Uint8Array: boolean,AssertionError: Failure: Cannot coerce to Uint8Array: boolean,AssertionError: Failure: Cannot coerce to Uint8Array: boolean,AssertionError: Failure: Cannot coerce to Uint8Array: boolean
    at MultiClient.send (/Users/z/git/ssh/node_modules/nkn-sdk/lib/multiclient/multiclient.js:377:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
这是什么错误？代码见截图

![image](https://user-images.githubusercontent.com/52188840/89724074-f6ac6500-da30-11ea-9765-91e4850d0389.png)

**Comment by yilunzhang** [comment]
这里传给 send 的数据是什么类型的呀？只能发送 string 或者 bytes(即 Uint8Array) 类型的数据

**Comment by eyun-tv** [comment]
nodejs 的buffer可以发送吗？

**Comment by yilunzhang** [comment]
可以的，Buffer 会按照 Uint8Array 的方式发送

**Comment by eyun-tv** [comment]
![image](https://user-images.githubusercontent.com/50322174/89724326-15602b00-da34-11ea-9065-3efaaff8ccb1.png)
我测试了，转成Uint8Array，还是不行
```

Uint8Array(76) [
    1, 189, 238,  50, 108,  50, 134, 230,  12, 178,  55, 203,
  249, 123, 171, 172,  64, 141, 123,  10, 207,  91, 102,  26,
  109, 234, 251,  51,  36, 199,  14, 186,  40, 141,  23, 143,
  252, 205, 140, 103, 106, 228, 131, 134,   4, 107, 123, 238,
   78, 223, 241,  70,  54,  84, 169,  33, 150, 247, 202,  85,
  145, 186, 189,  41,  16,  51,  21, 133,  94,  96, 176, 201,
   64, 206,  35, 233
]
Send response error: Error: failed to send with any client: AssertionError: Failure: Cannot coerce to Uint8Array: boolean,AssertionError: Failure: Cannot coerce to Uint8Array: boolean,AssertionError: Failure: Cannot coerce to Uint8Array: boolean,AssertionError: Failure: Cannot coerce to Uint8Array: boolean
    at MultiClient.send (/Users/z/git/ssh/node_modules/nkn-sdk/lib/multiclient/multiclient.js:377:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

Uint8Array(60) [
  224,  26,   0,  87,  79,   3,  54, 108,  96, 202, 178,
  153, 208,  41, 105, 248, 129, 132, 200, 131, 177, 111,
  191,  35, 115,  10, 153, 152, 116,   7,  38, 173,  66,
   71, 251, 237,  48, 210,  70, 153, 153, 115, 250, 174,
   83,  41, 189,  64, 165, 179,  41,  84, 160, 119, 205,
   11, 168, 150,  26,   8
]
```

**Comment by yilunzhang** [comment]
Log 里面提示的是 Send response error，也就是说是在接收端回复的时候传入的数据的问题

**Comment by yilunzhang** [comment]
我仔细看了一下你发的第一张截图，这里你是希望异步回复是嘛？那 onMessage 的时候需要返回 false，参见 readme 里面的这一段：
![image](https://user-images.githubusercontent.com/2791582/89724445-e6a46f00-d9b7-11ea-892b-037836003c8c.png)

**Comment by eyun-tv** [comment]
搞定了，我回头来写个技术文章，我做了一个tcp的端口转发，可以用来给ssh打洞，你们有技术交流群吗？

**Comment by yilunzhang** [comment]
赞！我们技术讨论最多的群是 Discord 群：https://discord.gg/c7mTynX 其次应该是论坛：https://forum.nkn.org/

此外这个不知道对你有没有用：https://github.com/nknorg/nkn-tunnel

**Comment by eyun-tv** [comment]
赞，我是想写一个分布式看电影的东西，先写个小东西练练手。
有一个问题，这个区块链网络有中央服务器吗，会不会海盗湾一样因为版权被封杀？

**Comment by yilunzhang** [comment]
没有任何中心化的服务器~ 网络里面的几万个节点（node）是全部等价的，client 只需要知道其中的任何一个就可以加入网络。现在 client 创建的时候默认会用官方的 seed 节点，但是如果访问或者性能有问题的话，可以在创建 client 的时候通过 rpcServerAddr 来制定~

**Comment by eyun-tv** [comment]
多谢多谢，感觉这个真的改变了互联网的模式，会诞生出很多杀手级的应用。

**Comment by eyun-tv** [comment]
@yilunzhang 我测试了一下 nkn-tunnel ，明显感觉比我自己用js sdk nkn.MultiClient     numSubClients: 4 进行 ssh要卡很多
，这可能是什么原因呢？
感觉不应该啊，go性能应该比js好才对。

**Comment by yilunzhang** [comment]
这个应该和语言关系不太大，因为瓶颈不在 CPU。你用的是 Session 模式嘛？nkn-tunnel 用的是 Session 模式，Session 模式的传输是保持顺序和可靠性的（和TCP兼容），好处是可以和其他 TCP 的程序直接兼容，但是如果有丢包或者乱序的情况，延迟会受到影响（但是带宽一般不会）。如果你没有用 Session 模式，那延迟应该会低一些~

**Comment by eyun-tv** [comment]
@yilunzhang 我思考了一下，既然是做的tcp端口数据转发，tcp本身就会保证数据的顺序，这边不需要再次确保顺序了。

**Comment by eyun-tv** [comment]
也就是如果乱序了 tcp 应该会丢包然后重传

**Comment by eyun-tv** [comment]
我想了一下，为了确保低延时并且可控，我可以尝试下Raptor Code喷泉码

**Comment by yilunzhang** [comment]
如果直接调用 multiclient 的 send 方法的话，底层的多个（默认 4 个）client 其实是会同时发送这个数据，来达到最高的可靠性和（在带宽不是瓶颈的情况下）最小的延迟，但是会浪费 3 倍的带宽。对于类似 IM、ssh 这种数据量非常少的情况，浪费的带宽是可以忽略不计的，所以是比较适合的。如果是想减少浪费的带宽的话，用 Erasure Coding 其实应该是一个不错的选择。

Session 模式就不太一样了，底层的多个 client 会发送完全不同的数据包。除非某个数据包超时会重传，否则是完全没有冗余数据的。可以理解为牺牲延迟来最大化带宽，比较适合文件传输这种对延迟不敏感，但是对带宽敏感的情况。协议的详情参见 https://forum.nkn.org/t/nkp-0009-nkn-transport-layer/1462/21?u=yilun
