### ISSUE TITLE
如果MultiClient.send调用成功，是否可以确认对方收到了消息？

### ISSUE THREAD

**Issue by eyun-tv** [nknorg/nkn-sdk-js#36]
因为我看当对地址不在线，调用会报错 Error: failed to send with any client: Error: Message timeout 。

所以我想明确一下，如果MultiClient.send调用成功，是否可以确认对方收到了消息？

**Comment by yilunzhang** [comment]
如果用默认的 option 调用 send，那返回的 promise resolve 的时候，就说明收到了对方的回复或者 ack，对方一定收到了消息。如果在 send 的参数里面传入了 noReply （https://docs.nkn.org/nkn-sdk-js/#sendoptions），那么 send 方法返回的 promise 会立刻 resolve，无法收到或者处理对方的回复或者 ack。

**Comment by eyun-tv** [comment]
多谢
