### ISSUE TITLE
建议 : 给onConnect的回调加上try catch，然后显示下错误信息

### ISSUE THREAD

**Issue by eyun-tv** [nknorg/nkn-sdk-js#38]
现在onConnect的回调函数出错，只会显示

Failed to connect to any client: undefined

调试很麻烦

建议加一个类似如下代码

```
try
   callback()
catch err
   console.error err
   console.trace()
   throw err

```

**Comment by yilunzhang** [comment]
这个是因为 nodejs 和 web 的 Promise.any 返回的错误类型是不同的，web 版本返回的是 AggregateError （https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any），所以 node 里面会显示undefined。这个我们需要兼容一下 nodejs

**Comment by yilunzhang** [comment]
1.1.8 已修复~
