### ISSUE TITLE
Use workers for sigchain calculations

### ISSUE THREAD

**Issue by losnappas** [nknorg/nkn-sdk-js#4]
Hey,

It might be a good idea to separate signature chain calculations into workers. Workers are widely supported, after all, and those calculations can lock up processing for a long time.

If we were to create one or more workers, for just the calculations, then that would improve the ease-of-use of this library.

Currently d-chat handles nkn related operations in one worker, which results in lock-ups and bad UX if one sends multiple messages quick succession, because sending and receiving are done in the same worker thread. But if this library calculated the signature chains in separate worker(s), then you could receive and send messages at the same time, without lock-ups.

I mean, you probably don't need a worker for receiving messages, but you do want one for sending them.

**Comment by yilunzhang** [comment]
It seems that in theory we can move the signature calculation to workers since it's eating up 90% of execution time with one single function based on my benchmark using Chrome dev tool. So we can send data to be signed to web workers using postMessage, and worker can send back result using postMessage as well. Does that sounds like a good idea to you?

Another question I have is that, I'm not sure I understand why the current web worker usage in d-chat leads to lock-ups and bad UX. I want to make sure it won't occur if we were to web workers for signatures.

**Comment by losnappas** [comment]
That sounds about right. Create worker(s), then post messages back and forth just like you said. One worker should probably be enough. More than one would make it faster, though, if that's feasible.

As for d-chat, it is somewhat unrelated. I just happen to route everything related to chatting through the worker, and that includes locally receiving messages. While the signatures are being calculated, the worker is at full capacity and cannot process next messages. I could work around that, but the fix presented here is probably better for d-chat and for this library.

**Comment by yilunzhang** [comment]
Version 1.0.5 now has web worker enabled. You can add `worker: true` to client/multiclient/wallet options to use it (https://docs.nkn.org/nkn-sdk-js/). Each client/wallet will have its own worker. If it works well, we can enable it by default in the next version.

**Comment by losnappas** [comment]
It seems to me that webpack does not like the "webworkify" package, which targets browserify, and throws errors.

That _might_ be because I'm trying to use them from within a worker, but I think it would make sense to let user have some more say in creation of worker, like this, for example:

```javascript
// Create a worker from the file
// For example webpack with worker-loader
import SigWorker from 'worker-loader!nkn-sdk/lib/common/worker.js'
const createWorker = () => new SigWorker();
const nkn = new MultiClient({
  workerFactory: createWorker,
})
```

I assume rollup (and other bundlers) will have some of the same problems, otherwise.

**Comment by yilunzhang** [comment]
I did some testing and found the problem: browserify webworkify requires that the worker exports a function that accepts self as argument, and all worker load should be done in that function; while standard web worker (like webpack worker loader) will just have worker body in the worker file. So I created another file `lib/worker/webpack.worker.js` that can be used by webpack.

In the new version (1.0.6) `worker` argument can also be a worker factory function (in addition to boolean value). But if you use web pack + worker loader, you don't need to provide it as now it will try both browserify and webpack worker loader. I tested with the following webpack config and it works well:
```
module: {
    rules: [
      {
        test: /\.worker\.js$/,
        use: {
          loader: 'worker-loader',
          options: { inline: true, fallback: false }
        }
      }
    ]
  }
```

**Comment by yilunzhang** [comment]
@losnappas Just in case you missed the github alert :)

**Comment by losnappas** [comment]
I've implemented the workers in a dev build, and they work well. The generator function is especially useful, because it gives control on how many workers are built in total.

**Comment by yilunzhang** [comment]
Sounds good! Let me close the issue then.
