### ISSUE TITLE
src地址有办法拿到buffer的原始数据吗？感觉原始数据应该是buffer吧。用hex字符串感觉挺浪费内存的

### ISSUE THREAD

**Issue by eyun-tv** [nknorg/nkn-sdk-js#40]
如题，尤其是连接数多的时候。

**Comment by eyun-tv** [comment]
配合nodejs的 map Map - JavaScript | MDN : https://t.cn/RqBlcDC
然后用 buf.toString('binary') 作为 key ，就很节省内存，想肉眼查看可以用 buf.toString('hex')
从 binary的string到hex的string也可以这样转换
Buffer.from(binary).toString('hex')

**Comment by yilunzhang** [comment]
src 字段原始数据就是 string，虽然 pubkey 部分都是 hex，但其实更一般的形式是 `identifer.pubkey`，其中 identifier 是任意的字符串，pubkey 是公钥的 hex 形式
