### ISSUE TITLE
可以考虑提供一个兼容 nodejs Stream 的接口，降低学习成本，同时可以方便对接各种中间件（比如压缩）

### ISSUE THREAD

**Issue by eyun-tv** [nknorg/nkn-sdk-js#41]
比如如果兼容 Stream接口，就可以很方便用pipe的加一个Brotli压缩，或者复用一些其他的nodejs中间件，比如流量统计什么的。

参考 ：
* Streams and Brotli compression in Node.js | by Linoy Zaga | Medium : https://t.cn/A6U9PZFS
* Node.js Stream - 基础篇 - 美团技术团队 : https://t.cn/A6U9v0zE
* How to create duplex streams with Node.js - a Nodejs programming tutorial for web developers | CodeWinds : http://codewinds.com/blog/2013-08-31-nodejs-duplex-streams.html

![image](https://user-images.githubusercontent.com/50322174/89789907-cf01ed80-db53-11ea-93a8-45170c5ae097.png)

**Comment by yilunzhang** [comment]
nodejs 的 stream 是需要 import 的，如果直接在 session 里面内置，会对浏览器环境有副作用（也会 import），所以目前没有原生支持。

另一方面，浏览器的 ReadableStream 和 WritableStream 是在 global scope 里面直接定义的，内置这个对 nodejs 没有副作用，所以现在 session 内置 ReadableStream 和 WritableStream。

目前我们比较推荐的方案是用第三方库把 ReadableStream 和 WritableStream 转换为 nodejs 的 stream~

**Comment by eyun-tv** [comment]
好
