### ISSUE TITLE
src是确认无法被伪造的吗？我没看底层协议，但是我猜是。就是想确认一下。

### ISSUE THREAD

**Issue by eyun-tv** [nknorg/nkn-sdk-js#42]
如题。

**Comment by yilunzhang** [comment]
只要消息是开启加密（默认开启）的，那就可以确认消息的发送者拥有 src 中的公钥部分对应的私钥，或者接受者自己的私钥。这个是由端到端加密的安全来保证的，详情可以参考 libsodium/Nacl 的密码学库。
