### ISSUE TITLE
nodejs 的 MultiClient.send 需要自己做拥塞控制吗？还是说底层已经做了

### ISSUE THREAD

**Issue by eyun-tv** [nknorg/nkn-sdk-js#44]
如图

**Comment by yilunzhang** [comment]
底层用的是 websocket，tcp 那边已经做了拥塞控制，所以一般是不用担心的

**Comment by eyun-tv** [comment]
是这样啊，不过tcp其实性能挺差的，有考虑过 quic 、 kcp 、Tsunami UDP之类协议吗？

* 科普：QUIC协议原理分析 - 知乎 : https://zhuanlan.zhihu.com/p/32553477
* skywind3000/kcp: KCP - A Fast and Reliable ARQ Protocol (快速可靠传输协议) : https://t.cn/RAbVYq9
* Tsunami UDP Protocol : http://tsunami-udp.sourceforge.net/
* 运用Tsunami UDP将大数据迁移至云中-InfoQ : https://t.cn/AipiLjIl

我知道有不少公司就基于udp专门做产品，感觉可能挺有市场的，比如

* 镭速传输-大文件传输软件,企业级大文件传输协议,跨境传输,跨国传输,企业大数据传输解决方案 : https://www.raysync.cn/
* Aspera - Overview | IBM : https://t.cn/A6UN3dG7
* 镭速(Raysync)与Aspera数据传输实时对比！ - 知乎 : https://zhuanlan.zhihu.com/p/58049868

针对吞吐和时延都可以单独用某种udp协议优化下

**Comment by yilunzhang** [comment]
TCP 只是在高丢包率的网络情况下性能会受到影响。对于低丢包率的情况下，TCP 在吞吐量方面已经做得非常好了，而新一些的TCP（如 TCP BBR）进一步在延迟方面也做得非常好。

实际上 NKN Node 也是支持 KCP 的，但是我们实测在大部分节点的网络环境下（VPS 节点的网络环境都很好），TCP 的吞吐量是远高于 KCP 的，所以 TCP 是 node-node 通讯的默认协议。

Client 和 node 之间的通讯协议就没什么可选的了，要兼容现在的主流浏览器，ws 肯定是首选。基于 UDP 的协议还是等浏览器兼容了再说吧 😂

**Comment by eyun-tv** [comment]
不单单是丢包，延时其实会影响tcp吞吐的。在跨国的时候，这一点会特别明显。
可以看这个对比。

数据传输优势！FTP 需要10小时，IBM Aspera 只需8.4秒！ : https://t.cn/A6UNrj7B
也就是说，原本在美国国内 FTP 需要超过10小时才能传完的数据，现在 Aspera 只需 8.4 秒就能搞定！
正因为它的逆天能力，很多知名公司在用它传输数据。

也可以看看SRT协议。
拆解SRT：新UDP视频传输协议 : https://t.cn/A6UNr0gN

**Comment by eyun-tv** [comment]
![image](https://user-images.githubusercontent.com/50322174/89958741-40818f00-dc6d-11ea-959c-2c3609d489e6.png)
为什么 TCP 协议有性能问题 ·（一） - InfoQ : https://www.infoq.cn/article/PsxDNqXU0oJdbxk5a9jG

**Comment by yilunzhang** [comment]
延迟是有影响的，但只有 `RTT > buffer / throughput` 的时候才会对 throughput 有影响，当延迟小于这个值的时候并不会成为带宽的瓶颈。所以实际中不同的网络环境适合的传输协议是不一样的。NKN Node 的网络环境大多都是非常好的，无论是理论分析还是实际测试，TCP 都是非常适合的。一般只有 Node 和 Client 之间的传输才会出现网络环境比较差导致的高丢包或者高延迟情况，但是就像我上面说的，Client 目前为了兼容性并不能选择 UDP。

**Comment by eyun-tv** [comment]
如果用go的sdk，是可以支持udp的吗？

**Comment by yilunzhang** [comment]
目前还不支持的~ 现在 client 这边只支持 websocket，这样所有语言的 SDK 没有协议层面的区别。以后可能会添加更多协议支持

**Comment by eyun-tv** [comment]
多谢，期待。
我的为ssh穿透优化的演示demo就快开发完了。
在复杂网络环境下还是有点小卡，我刚刚就是想看看有没有办法继续优化下。

**Comment by yilunzhang** [comment]
棒棒哒！也期待你的作品！
