### ISSUE TITLE
noReply:true 的时候返回值不是null ，和文档不一致

### ISSUE THREAD

**Issue by gcxfd** [nknorg/nkn-sdk-js#45]
文档是这么写的
https://docs.nkn.org/nkn-sdk-js/#multiclientsend

> Promise<ReplyData>: A promise that will be resolved when reply or ACK from destination is received, or reject if send fail or message timeout. If dest is an array with more than one element, or options.noReply=true , the promise will **resolve with null** as soon as send success.

现在返回是的类似
```
Uint8Array(8) [
  148,  30, 78,  76,
   50, 211,  5, 221
]
```

**Comment by yilunzhang** [comment]
多谢指正！1.1.9 版本已修复~
