### ISSUE TITLE
Request: API method to get wallet transactions

### ISSUE THREAD

**Issue by markg85** [nknorg/nkn-sdk-js#46]
Hi,

I went through the [API](https://docs.nkn.org/nkn-sdk-js/#wallet) but can't seem to find any method that gives me a list of transactions.

Having such an API call would be awesome!
I asked about it more often and i think the answer thus far was that it's a hidden feature somewhere. I forgot where though.

Cheers,
Mark

**Comment by yilunzhang** [comment]
This is not available because NKN node has no efficient way to do that, just like other blockchains using balance model (e.g. Ethereum). The most convenient way is to use blockchain explorer. You might want to check rule110's nkn openapi. We hosted one openapi node at https://openapi.nkn.org/docs/
