### ISSUE TITLE
请问如何获取消息和ack的数字签名

### ISSUE THREAD

**Issue by gcxfd** [nknorg/nkn-sdk-js#49]
比如我想做一款去中心化的聊天应用，每个人可以存储和分发其他人的历史消息。
那么就需要存下对方发过来消息和ack的签名，来证明这条信息是其他人发的。
现在的sdk，如何获取消息的数字签名？如何通过地址+消息计算数字签名来校验？

**Comment by yilunzhang** [comment]
NKN 客户端里面的消息不是用签名来证明的，而是用 AEAD （更具体地说是 XSalsa-Poly1305）来验证和加密的。但是这里的验证和解密只有对方的私钥持有者才能进行的，所以不能像签名一样让任何人都可以验证。如果你需要任何人都可以验证消息历史的话，可能需要自己来把签名作为消息协议的一部分。

**Comment by gcxfd** [comment]
好的，另外 nkn 如何获取更多 rpc server 呢？有接口吗？

**Comment by yilunzhang** [comment]
multiclient 可以通过 multiclient.clients 来获得当前的所有 client，每个 client 可以通过 client.node 来获得他当前连接的节点~但这些节点都不是官方的哈，所以比较适合作为备用节点
