### ISSUE TITLE
我看源码中有maxClientMessageSize，消息长度是不能超过这个吗？还是说会自动拆包和组装

### ISSUE THREAD

**Issue by gcxfd** [nknorg/nkn-sdk-js#54]
没仔细看，正在做基于nkn的热更新（能自动更新是第一步），问一下。

**Comment by yilunzhang** [comment]
不能超过这个，否则会被 node 端直接丢弃。但是实际上非常非常不建议用 send 直接发送 1MB 以上的大包，甚至 100KB 以上我个人觉得也太大了。client send 方法发送的包可以理解为一个 UDP 数据包，直接用一个 UDP 数据包发送大量数据对于性能、丢包率这些都有很大的影响，而且 multiclient 发送的数据还是冗余的。凡是大一些的数据，都建议用 session 模式，session 模式的数据都会被拆解成为不超过 session MTU 的数据包，分别发送，然后在对方组装起来。
