### ISSUE TITLE
能为app开发框架Hbuilder做个专门的插件吗

### ISSUE THREAD

**Issue by dachangding** [nknorg/nkn-sdk-js#56]
我们习惯于用开发框架Hbuilder做app，目前，我们开发的两个app需要接入nkn技术。
在Hbuilder里，按照nkn-sdk-js的说明操作，我们没能成功地实现通讯，不管是使用nodejs还是在本地web-view里面，我们都只能和node建立起连接，没能正常地实现两点通讯
Hbuilder在中国内有很多开发者使用，如果能够有针对Hbuilder优化过的sdk，或者Hbuilder专门的nkn插件，我们觉得会有一大批开发者跟进，如果能实现就太感谢了

**Comment by yilunzhang** [comment]
Hbuilder的 js 环境和 nodejs 或者浏览器有什么区别呀？examples/client.js 里面的代码运行会有问题吗？比如本地用 nodejs 运行 examples/client.js 是可以正常收发消息的：
```
> node examples/client.js 
Secret seed: 9601a465df91703cfaa4ce92b441d87828071cef4455174d9176e6c62716911c
Send message from alice.7b0c38b01bfe3c1c96c9e62fd283c88291cc5046c3d99992675d44d1c461f903 to bob.ec8f4bc6ad73fba13ce492554494ec7ac0579149703037dbff2f0b1a909e537d
Receive encrypted message "Hello world!" from alice.7b0c38b01bfe3c1c96c9e62fd283c88291cc5046c3d99992675d44d1c461f903 after 107 ms
Receive reply "Well received!" from bob.ec8f4bc6ad73fba13ce492554494ec7ac0579149703037dbff2f0b1a909e537d after 202 ms
```

**Comment by dachangding** [comment]
你是在hbuilder里面测试的吗？我在里面用nodejs 测试example得到no PRNG呢？

**Comment by dachangding** [comment]
> Hbuilder的 js 环境和 nodejs 或者浏览器有什么区别呀？examples/client.js 里面的代码运行会有问题吗？比如本地用 nodejs 运行 examples/client.js 是可以正常收发消息的：
> 
> ```
> > node examples/client.js 
> Secret seed: 9601a465df91703cfaa4ce92b441d87828071cef4455174d9176e6c62716911c
> Send message from alice.7b0c38b01bfe3c1c96c9e62fd283c88291cc5046c3d99992675d44d1c461f903 to bob.ec8f4bc6ad73fba13ce492554494ec7ac0579149703037dbff2f0b1a909e537d
> Receive encrypted message "Hello world!" from alice.7b0c38b01bfe3c1c96c9e62fd283c88291cc5046c3d99992675d44d1c461f903 after 107 ms
> Receive reply "Well received!" from bob.ec8f4bc6ad73fba13ce492554494ec7ac0579149703037dbff2f0b1a909e537d after 202 ms
> ```

或许是我的环境搭建有问题，我再试试

**Comment by yilunzhang** [comment]
> 你是在hbuilder里面测试的吗？我在里面用nodejs 测试example得到no PRNG呢？

不是，我就是在标准的 nodejs 里面测试的，所以我才好奇 hbuilder 和标准的 nodejs/浏览器环境有什么区别

**Comment by yilunzhang** [comment]
no prng 应该是 nacl 这个依赖的问题，你能尝试一下用 `nacl.setPRNG` 来手动指定随机数生成器？详见 https://github.com/dchest/tweetnacl-js#random-bytes-generation

**Comment by yilunzhang** [comment]
Closing for now due to inactivity.
