### ISSUE TITLE
vite里无法调用。怎么处理

### ISSUE THREAD

**Issue by jinmao88** [nknorg/nkn-sdk-js#57]
vue3+vite  无法调用

**Comment by yilunzhang** [comment]
有具体的信息吗？你们的环境和 node.js 或者浏览器环境有什么区别吗？

**Comment by jinmao88** [comment]
node 14.13.1
yarn 1.22.4
vite 1.0.0-rc.9
vue 3.0.2








![image](https://user-images.githubusercontent.com/50581550/99220104-ffbf8600-2818-11eb-8e1f-a0cf14735c68.png)

**Comment by yilunzhang** [comment]
这个是 typescript 的错误么？nkn-sdk-js 不是用 typescript 写的，所以没有提供 typescript 的类型定义

**Comment by jinmao88** [comment]
vite对包有要求
好像是内部有node模块

**Comment by yilunzhang** [comment]
有具体的提示么？nkn-sdk-js 在浏览器里面使用是没问题的，如果需要快速测试的话可以用 `dist` 目录下提供好的 js bundle

**Comment by jinmao88** [comment]
直接用JS?
我
试试吧

**Comment by jinmao88** [comment]
vite没法用外部JS的方式

**Comment by jinmao88** [comment]
Error: ENOENT: no such file or directory, stat 'path'
 Error: ENOENT: no such file or directory, stat 'crypto'

**Comment by yilunzhang** [comment]
你如果尝试引入这个库 `tweetnacl` 会有问题吗？

**Comment by jinmao88** [comment]
这个库可以
引入 编译没什么问题

**Comment by jinmao88** [comment]
[vite] Dep optimization failed with error:
Dependency libsodium is attempting to import Node built-in module path.
This will not work in a browser environment.
Imported by: node_modules\libsodium\dist\modules\libsodium.js

**Comment by yilunzhang** [comment]
这就比较麻烦了，[libsodium](https://github.com/jedisct1/libsodium.js) 是一个必要的依赖，而且他实际上是支持浏览器环境的……

**Comment by jinmao88** [comment]
这个还好 可以配置

**Comment by yilunzhang** [comment]
你可以测试一下刚刚发布的 1.2.0 版本吗？除了 libsodium 以外的依赖应该都解决了

**Comment by jinmao88** [comment]
Error: ENOENT: no such file or directory, stat 'crypto'
 Error: ENOENT: no such file or directory, stat 'path'
还是这2个报错

![image](https://user-images.githubusercontent.com/50581550/99328041-35ff1300-28b6-11eb-968f-b98355cb3f72.png)
这是浏览器的警告

**Comment by yilunzhang** [comment]
那就是第三方库引入的了。我看了一下，貌似只有 libsodium 引入了这两个库，而且他是做的动态 import，即只有在 nodejs 环境里面才会引入，所以实际上在浏览器环境里面是不会调用的。你能设置成让他打包的时候忽略这两个库么？

**Comment by jinmao88** [comment]
好像不行

**Comment by jinmao88** [comment]
截图的是开发环境

**Comment by jinmao88** [comment]
除了用sdk 还有别的方式么

**Comment by jinmao88** [comment]
https://github.com/anncwb/vue-vben-admin  可以拉这个项目 然后添加模块测试
