### ISSUE TITLE
vite2 依赖引入后使用报错

### ISSUE THREAD

**Issue by jinmao88** [nknorg/nkn-sdk-js#63]
import没问题
let wallet = new nkn.Wallet({ password: 'password' });
new的时候就报错
![image](https://user-images.githubusercontent.com/50581550/104415936-dcf9e580-55ad-11eb-9c3c-d5a4cbdefbb7.png)
node：14.15.3
vite:2.0.0-beta.12
vue:3.0.5

**Comment by yilunzhang** [comment]
你这是用的 dists 里面的 nkn.js/nkn.min.js 还是自己用 babel 之类的工具打包的 js ？nkn-sdk-js 的源代码里面是没有出现 arguments 的，但是在用 babel 或者其他方法打包的时候有可能生成，感觉这个是打包时候的配置问题。

**Comment by jinmao88** [comment]
npm 安装的依赖

**Comment by yilunzhang** [comment]
npm 安装的话应该是你那边生成的 nkn-sdk.xxx.js。这个生成的过程你能够配置么？应该是这里出现了问题。如果你需要例子的话可以看下这里对于 babel 的配置 https://github.com/nknorg/nkn-sdk-js/blob/master/babel.config.json

**Comment by jinmao88** [comment]
不是babel VITE2的相关配置有吗

**Comment by yilunzhang** [comment]
没有，我们之前都没有用过 vite。不过我刚才搜了一下，vite 貌似也是可以用 babel 或者其他类似工具的，比如：https://www.npmjs.com/package/vite-babel-plugin

**Comment by JustroX** [comment]
Hello. It seems I also got into the same bug 
```
Uncaught ReferenceError: arguments is not defined
```

I'm using webpack and I can't get it to work. Here's my config for packaging the module using babel.
```ts

export default {
  module: {
    rules: [
      {
        test: /\.m?js$/,
        include: resolve(__dirname, '/node_modules/nkn-sdk/'),
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              [
                '@babel/env',
                {
                  targets: {
                    node: '8',
                  },
                },
              ],
              '@babel/preset-flow',
            ],
            plugins: [
              '@babel/plugin-proposal-class-properties',
              '@babel/plugin-proposal-export-default-from',
              '@babel/plugin-proposal-export-namespace-from',
            ],
          },
        },
      },
    ],
  },
} as Configuration;
```

**Comment by yilunzhang** [comment]
@JustroX Why you need to use babel on nkn-sdk again? When you install nkn-sdk-js with npm or yarn, you are using the version that is already transpiled using webpack/babel (the one inside /lib), and you don't need to do it again.

**Comment by JustroX** [comment]
Thanks for the response. Honestly, I'm just trying a lot of approaches, just thought that I need to transpile it again (inferring from the conversation above, I'm so sorry Google Translate isn't accurate). However, just importing it results to the following error:

```
Uncaught ReferenceError: arguments is not defined
```
Currently, as a workaround, I just include the .min.js on a script tag <script>. However, I can't use the type definitions for that.

**Comment by yilunzhang** [comment]
You can see from [here](https://github.com/nknorg/nkn-sdk-js/blob/master/package.json#L12) that the difference between just importing (which uses `lib/`) and `nkn.js` is just a browserify:

`browserify lib/index.js -s nkn --outfile dist/nkn.js`

Have you tried using browserify to transpile your js?

**Comment by JustroX** [comment]
That makes sense. Currently, I don't know how to do that inside of Angular. I'll explore that tomorrow. I'll keep you posted. Thank you
