### ISSUE TITLE
wrong seed size

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [nknorg/nkn-sdk-js#66]
Hello, I tried to import some older private keys and they are all a few characters longer than the one's being used today.. how can I claim my tokens? 

```
Example Format:

NL69YPb8hFJjfXXNKM6EzPhcWp24XxxPXx
0224a2122514717fffef2496534cbaf4fe8c708acd594e0dfc173b256e6aec222a


```

**Comment by yilunzhang** [comment]
It seems that you are trying to import a non-NKN mainnet address, e.g. testnet address, Ethereum address, etc. Your address protocol and token are incompatible with NKN mainnet, so is your token inside the address.
