### ISSUE TITLE
multiClient返回的wss节点中包含有nknlabs.io, 被谷歌检测为不安全, 导致使用sdk的网站也被谷歌浏览器提示为不安全

### ISSUE THREAD

**Issue by avenger9527** [nknorg/nkn-sdk-js#76]
你好!
使用的浏览器 : 谷歌Chrome
我们的https网站使用了这个sdk, 一打开我们的网站就会调用new MultiClient(), 接着就获取例如下面的wss://144-202-102-11.ipv4.nknlabs.io节点, 然后直接提示"您要访问的是诈骗网站
144-202-102-11.ipv4.nknlabs.io 上的攻击者可能会诱骗您做一些危险的事情..."
![image](https://user-images.githubusercontent.com/72054514/136850239-ec6a2ab3-a6ea-48b9-8765-cdde67e52623.png)
然后我在谷歌安全透明度里查询到这个地址是不安全的:
https://transparencyreport.google.com/safe-browsing/search?url=144-202-102-11.ipv4.nknlabs.io
接着我修改 144-202-102-11.ipv4.nknlabs.io中除了'nknlabs.io'的其他任意内容都是报不安全, 但是只要修改了'nknlabs.io'就没事了, 所以我猜测是'nknlabs.io'被谷歌标记为了不安全. 
同时我在谷歌搜索nknlabs.io的时候发现有些网站是这样的:
![549e74d89e5b2f46abf162f778562bd](https://user-images.githubusercontent.com/72054514/136851604-4fc14c87-77ed-4ecc-952c-bbdffbf6abe9.png)
会不会是某些这种网站存在钓鱼行为导致了谷歌直接屏蔽了'nknlabs.io' ?
这个问题其他浏览器没有, 只是谷歌浏览器, 请问下这个有解决方案吗?

**Comment by yilunzhang** [comment]
`ipv4.nknlabs.io` 这个域名其实只有一个功能，就是把 `a-b-c-d.ipv4.nknlabs.io` 的子域名解析为 `a.b.c.d` 这个 IP，其中 `a.b.c.d` 可以是任意 IP 地址。我觉得是你说的情况，应该是有钓鱼网站的 IP 地址用了这个服务，导致 Chrome 把整个域名给标记为不安全的了。我们已经向他们反馈错误了（点击详情那个按钮里面有），不过鉴于谷歌的客服一般比较慢，他们未必能及时响应。再次之前，最简单的办法是采用 http 而不是 https，这样就不会用 `ipv4.nknlabs.io` 这个域名来解析 IP 地址了

**Comment by yilunzhang** [comment]
貌似有作用了，我这边现在测试的话谷歌已经没有提示了~
