### ISSUE TITLE
1. 当encrypt:false的时候，src地址有可能被伪造吗？ 2. publish/subscriber 发送接收的内容是明文吗？

### ISSUE THREAD

**Issue by gcxfd** [nknorg/nkn-sdk-js#78]
1. 当encrypt:false的时候，src地址有可能被伪造吗？ 
2. publish/subscriber 发送接收的内容是明文吗？

**Comment by yilunzhang** [comment]
> 1. 当encrypt:false的时候，src地址有可能被伪造吗？

理论上有这个可能性。实际上可能需要恶意 client 和 node 的配合，但是还是存在这种可能性的。所以默认是开启端到端加密的。

> 2. publish/subscriber 发送接收的内容是明文吗？

这个和点到点的消息一样，开启了加密（默认开启）就是端到端加密的，关闭了就是明文。
