### ISSUE TITLE
Opening a session and keeping it open seems to increase memory usage (JS)

### ISSUE THREAD

**Issue by sce9sc** [nknorg/nkn-sdk-js#79]
Hi , First of all I must say that this is an incredible work. 
The examples are a very helpful. I came across a problem when trying to send a file using session and saw that memory was increasing. 
Using nkn-sdk-js  javascript lib and the examples for session. I found that by opening a session and leaving it open memory is increasing .

Do you have any ideas why? 
Should the session be closed and reopen whenever someone sends something through it?

I am using node version 14.16.0
"nkn-sdk": "^1.2.0",

**Comment by yilunzhang** [comment]
Are you running the `examples/session.js`? As a simple example, it keeps all random data generated and received in memory (both sender and receiver side), and that might be the reason. In practice, the sender side should read the data from somewhere (e.g. disk), and the receiver side should write data to somewhere (e.g. disk), this way the memory usage will not increase and data is transmitted. You can find a more comprehensive and working example at https://github.com/nknorg/nftp-js/blob/master/main.js

Feel free to let me know if you have more questions!

**Comment by sce9sc** [comment]
I am not sending anything I just opened a session nothing else

**Comment by yilunzhang** [comment]
Thanks for the details! I did reproduced and located the issue. It's caused by this library `@nodeguy/channel`. I ended up with making a copy of its code in project and fixed it there ([this PR](https://github.com/nknorg/ncp-js/pull/10)). This issue should have been solved in both the latest master branch and published package (v1.2.1). Really appreciated your info!

**Comment by sce9sc** [comment]
I am glad that I helped.

Unfortunately after installing the 1.2.1 version and tried to run the code I got 

```
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/sce9sc/Documents/Work/testNknLatestNode/node_modules/@nkn/ncp/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:683:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/sce9sc/Documents/Work/testNknLatestNode/node_modules/nkn-sdk/lib/multiclient/multiclient.js:8:35) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

**Comment by yilunzhang** [comment]
Replied to you in #82
